[package]
name = "eegui"
version = "0.1.0"
authors = ["GUOHUA LI"]
edition = "2021"


[dependencies]
#serde  = { version = "1", features = ["derive"], optional = true }
egui   = "0.23.0"
eframe = "0.23.0"
emath  = "0.23.0"
brainflow = { path = "../brainflow" }

